use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use once_cell::sync::Lazy;

use crate::tag_registry::TAG_REGISTRY;

/// High-level correlation id used across requests/subscriptions.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CorrelationId {
    U64(u64),
    /// Safe tag; held by the library to ensure backing memory outlives in-flight ops.
    Tag(Arc<str>),
}

// Global monotonic counter for autogenerated integer correlation ids used in
// high-level helpers. This keeps ids unique across the process while still
// being cheap to generate.
static NEXT_CORRELATION_ID: Lazy<AtomicU64> = Lazy::new(|| AtomicU64::new(1));

impl CorrelationId {
    /// Allocate a new unique u64-based correlation id.
    pub fn next() -> Self {
        let v = NEXT_CORRELATION_ID.fetch_add(1, Ordering::Relaxed);
        CorrelationId::U64(v)
    }

    pub fn as_u64(&self) -> Option<u64> {
        match self {
            CorrelationId::U64(v) => Some(*v),
            _ => None,
        }
    }

    pub fn as_tag(&self) -> Option<&str> {
        match self {
            CorrelationId::Tag(s) => Some(s.as_ref()),
            _ => None,
        }
    }

    pub(crate) fn to_ffi_u64(value: u64) -> blpapi_sys::blpapi_CorrelationId_t {
        let mut cid = unsafe { std::mem::zeroed::<blpapi_sys::blpapi_CorrelationId_t>() };
        unsafe { blpapi_sys::blpapiext_cid_from_u64(&mut cid as *mut _, value) };
        cid
    }

    pub(crate) fn to_ffi_ptr(ptr: *const core::ffi::c_void) -> blpapi_sys::blpapi_CorrelationId_t {
        let mut cid = unsafe { std::mem::zeroed::<blpapi_sys::blpapi_CorrelationId_t>() };
        unsafe { blpapi_sys::blpapiext_cid_from_ptr(&mut cid as *mut _, ptr) };
        cid
    }

    pub(crate) fn to_ffi_autogen() -> blpapi_sys::blpapi_CorrelationId_t {
        let mut cid = unsafe { std::mem::zeroed::<blpapi_sys::blpapi_CorrelationId_t>() };
        unsafe { blpapi_sys::blpapiext_cid_autogen(&mut cid as *mut _) };
        cid
    }

    pub(crate) fn to_ffi(&self) -> blpapi_sys::blpapi_CorrelationId_t {
        match self {
            CorrelationId::U64(v) => Self::to_ffi_u64(*v),
            CorrelationId::Tag(s) => {
                // Register the tag so we can reliably look it up again when decoding
                // correlation ids from incoming messages.
                let (ptr, _arc) = TAG_REGISTRY.register(s.as_ref());
                Self::to_ffi_ptr(ptr)
            }
        }
    }
}


